resources:
  - type: storage.v1.bucket
    name: sls-serverless-gcp-nodejs-dev-1634917869494
    properties:
      location: us-central1
  - type: gcp-types/cloudfunctions-v1:projects.locations.functions
    name: serverless-gcp-nodejs-dev-first
    properties:
      parent: projects/spheric-mesh-329815/locations/us-central1
      availableMemoryMb: 256
      runtime: nodejs10
      timeout: 60s
      entryPoint: http
      function: serverless-gcp-nodejs-dev-first
      sourceArchiveUrl: >-
        gs://sls-serverless-gcp-nodejs-dev-1634917869494/serverless/serverless-gcp-nodejs/dev/1634929251966-2021-10-22T19:00:51.966Z/serverless-gcp-nodejs.zip
      labels: {}
      httpsTrigger:
        url: path
  - type: gcp-types/cloudfunctions-v1:projects.locations.functions
    name: serverless-gcp-nodejs-dev-second
    properties:
      parent: projects/spheric-mesh-329815/locations/us-central1
      availableMemoryMb: 256
      runtime: nodejs10
      timeout: 60s
      entryPoint: helloPubSub
      function: serverless-gcp-nodejs-dev-second
      sourceArchiveUrl: >-
        gs://sls-serverless-gcp-nodejs-dev-1634917869494/serverless/serverless-gcp-nodejs/dev/1634929251966-2021-10-22T19:00:51.966Z/serverless-gcp-nodejs.zip
      labels: {}
      eventTrigger:
        eventType: providers/cloud.pubsub/eventTypes/topic.publish
        resource: projects/spheric-mesh-329815/topics/my-topic
